database:
  dbtype: 'sqlite'
  dbpath: './data/cves.db'
  sqlpath: './script/cves-create.sql'

github:
  graphql: 'https://api.github.com/graphql'
  repo: 'threat-broadcast'
  owner: 'lyy289065406'
  gtk: ""                # Github Token，若非空值则使用 Github Actions 发送播报邮件
  auto_commit: True                      # 使用 Github Actions 时不需要开启：自动提交变更到仓库（可自动归档、生成 Github Page）
  
crawler:
  top: 30                                 # 播报时每个来源最多取最新的前 top 个 CVE

notify:
  mail_smtp: '10.88.5.102'
  mail_user: 'hjzhu@hillstonenet.com'     # 用于发送播报信息的邮箱账号
  mail_pass: "qwerASDF456."
    #qq_user: ''                    # 用于向 QQ 群发送播报信息的 QQ 账号
    #qq_pass: ""

